motis-project/prima

src/routes/taxi/+page.svelte
remove logic for changing availabilities on client side
=> Remove unnecessary logic

src/lib/Location.ts, src/lib/api.ts, src/lib/collection_utils.ts, src/lib/coordinates.ts, src/lib/location.ts, src/routes/api/booking/+server.ts
Only use primitives as return type of keyfn of groupBy.
Insert addresses of start and target of the request into db in booking_api.
=> Booking api

src/lib/api.ts, src/routes/(user)/company/+page.server.ts
In company route
If check fails the form is considered invalid
=> Check whether address given by user is in selected community

test_data/default/company.sql
Companies address, community and compulsory-area should match now
=> Adjust test data

src/routes/(user)/company/+page.server.ts
community and zone were swapped
=> Fix bug in company route

src/lib/server/booking/getDirectDrivingDurations.ts, src/lib/server/util/oneToManyCarRouting.ts
if they do not contain a duration
=> Represent entries of motis response as undefined

src/lib/server/booking/bookRide.ts
getBookingAvailability was sometimes called with parameters in wrong order
=> fix bug in bookRide

src/lib/server/booking/insertion.ts, src/lib/server/util/interval.ts
=> Replace Interval.round with local function

src/lib/i18n/de.ts, src/lib/i18n/en.ts, src/lib/i18n/translation.ts, src/lib/server/verifyPhone.ts, src/routes/account/settings/+page.server.ts, src/routes/account/settings/+page.svelte, src/routes/account/signup/+page.server.ts
users can change their phone number
=> Users may only change their own password

src/lib/i18n/de.ts, src/lib/i18n/en.ts, src/lib/i18n/translation.ts, src/routes/(customer)/routing/ConnectionDetail.svelte, src/routes/(customer)/routing/ItineraryList.svelte
fixing #272 entailed reworking spacing a bit...
=> Styling for long names

src/routes/(customer)/routing/+page.svelte
in combination with motis-project/motis#793 closes #281
=> Limit maxTravelTime to 24h

src/lib/i18n/de.ts, src/lib/i18n/en.ts, src/lib/i18n/translation.ts, src/routes/(customer)/routing/ConnectionDetail.svelte
=> Verbindungsdetails: Collapse Fußweg zum Taxi auf der letzten Meile

src/lib/i18n/de.ts, src/lib/i18n/en.ts
Customer is liable to pay the call-out-fee(instead of full cost) Customer is required to cancel 1 (instead of 24) hour early to not be liable
=> Adjust message for customer cancelling a request

migrations/2025-04-07.js, src/lib/i18n/de.ts, src/lib/i18n/en.ts, src/lib/i18n/translation.ts, src/lib/server/db/index.ts, src/lib/ui/DisplayAddresses.svelte, src/routes/(customer)/bookings/+page.server.ts, src/routes/(customer)/bookings/+page.svelte, src/routes/(customer)/bookings/[slug]/+page.server.ts, src/routes/(customer)/bookings/[slug]/+page.svelte, src/routes/(customer)/routing/+page.server.ts, src/routes/(customer)/routing/+page.svelte, src/routes/(customer)/routing/ItinerarySummary.svelte, src/routes/taxi/availability/+page.server.ts
Fix: in bookings the displayed addresses corresponded to the odm part of the journey. Now the addresses matching start and end of the full journey are displayed.
=> Allow users to store itineraries with no odm

migrations/2025-04-24-json-and-latlng-precision.js, src/lib/server/db/index.ts, src/routes/(customer)/bookings/+page.server.ts, src/routes/(customer)/bookings/[slug]/+page.server.ts, src/routes/(customer)/rating/[slug]/+page.server.ts, src/routes/(customer)/routing/+page.server.ts
journey: change type of json to jsonb from string
event: change type of lat and lng to double precision from real
=> Alter Database columns in tables journey and event

docker-compose.yml, monitoring/blackbox.yml, monitoring/grafana-dashboard.json, monitoring/prometheus.yml, monitoring/rules.yml, monitoring/sql/sql.yml
Not sure if it even makes sense to commit/merge this, particularly the docker-compose.yaml. I have not committed alertmanager.yml, since it contains sensitive info.
Is already deployed as is.
=> Monitoring

driver-app/app/build.gradle.kts, driver-app/app/src/main/java/de/motis/prima/TourPreview.kt, driver-app/app/src/main/java/de/motis/prima/Tours.kt, driver-app/app/src/main/java/de/motis/prima/data/DataRepository.kt, driver-app/app/src/main/java/de/motis/prima/viewmodel/ToursViewModel.kt, driver-app/build.gradle.kts, driver-app/gradle.properties, driver-app/gradle/libs.versions.toml, driver-app/gradle/wrapper/gradle-wrapper.properties
handle cancelled tours correctly in driver app + fix dependencies and android settings
=> handle cancelled tours, dependencies, android settings

driver-app/app/build.gradle.kts, driver-app/app/src/main/java/de/motis/prima/Nav.kt, driver-app/app/src/main/java/de/motis/prima/TourPreview.kt, driver-app/app/src/main/java/de/motis/prima/Tours.kt, driver-app/app/src/main/java/de/motis/prima/data/DataRepository.kt, driver-app/app/src/main/java/de/motis/prima/viewmodel/ToursViewModel.kt
non-crucial improvements. highlight tours that have been push notified.
=> driver-app highlight new tours

src/lib/server/booking/evaluateRequest.ts, src/lib/server/booking/insertion.ts
This has the advantage that during weekends, it is prohibited to work on the code, since tests will probably fail then ;)
=> only allow booking for weekend until Friday 18:00

package.json, scripts/updateDatabaseDurations.ts
Updates the fields prevLegDuration, nextLegDuration and directDuration
=> Add a script for updating durations in the database
